remove docker-completion from ansible script (#48)
The package is already included in docker:

```
Error: Cannot install docker-completion because conflicting formulae are installed.
  docker: because docker already includes these completion scripts
```